#!/usr/bin/env bash
# shellcheck disable=SC2154
#configures a new Ubuntu machine nginx

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a basic index page
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx to add custom response header
custom_header="add_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/# server_tokens off;/# server_tokens off;\\n\t$custom_header/" /etc/nginx/nginx.conf

# Restart Nginx service
sudo service nginx restart
