#!/usr/bin/env bash
# Create a symbolic link to the default Nginx site config, Start the service, Restart killing the first Nginx process
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
