#!/usr/bin/env bash

# This script displays a list of currently running processes.

# Use the 'ps' command with the 'faux' options to list all processes in a full format,
# including those of other users and with additional information.
ps faux
