#!/usr/bin/env bash

# Bash script (init script) to manage the manage_my_process script.

# Function to start the manage_my_process script.
start_manage_my_process() {
    ./manage_my_process &      # Start manage_my_process in the background
    echo $! > /var/run/my_process.pid    # Store the PID of manage_my_process in /var/run/my_process.pid
    echo "manage_my_process started"
}

