#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash".
# It achieves this without using the 'ps' command, as per the requirements.
# We utilize the 'pgrep' command as an alternative.
pgrep -l bash
