#!/usr/bin/env bash

# This script displays the PID (Process ID) along with the process name of all processes
# whose name contains the word "bash".

# Use the 'pgrep' command to search for processes with the name "bash" and display their
# PID and process name using the '-l' option.
pgrep -l "bash"
