#!/usr/bin/env bash

# Bash script to terminate the "To infinity and beyond" loop process.

# Use the 'pgrep' command to find the Process ID (PID) of the process with the name "4-to_infinity_and_beyond".
# The '-f' option allows pgrep to match against the full command line of the process.
# The PID of the "To infinity and beyond" loop process is stored in the 'process_pid' variable.

# Use the 'kill' command to send a termination signal to the process identified by the PID stored in 'process_pid'.
# This will stop the "To infinity and beyond" loop.

kill "$(pgrep -f 4-to_infinity_and_beyond)"
