#!/usr/bin/env bash
# This script displays "to infinity and beyond" indefinitely
# with a sleep of 2 seconds between each iteration.
# It responds to a SIGTERM signal by echoing "I am invincible!!!"

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
