#!/usr/bin/env bash

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file in the home directory
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost$/127.0.0.2\tlocalhost/' ~/hosts.new
sed -i '/.*facebook.com/d' ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new

# Copy the modified hosts file back to /etc/hosts with sudo
sudo cp ~/hosts.new /etc/hosts

echo "Changes applied. You can now test with 'ping'."

# Clean up the temporary file
rm ~/hosts.new
